### PR TITLE
All rental functions integrated and working

### PR DESCRIPTION
**Pull request by mridul4101**

### CODE REVIEW

**Comment by mridul4101** [comment]
Delete button in MyProduct/address is not responsive

**Review by maheshrapelli141 — DISMISSED** [review]

**Comment by mridul4101** [comment]
Home Search and Product delete isn't functional

**Comment by mridul4101** [comment]
Home Search is fixed

**Comment by mridul4101** [comment]
Carousel page fixed

**Review by maheshrapelli141 — APPROVED** [review]

**Review by TarunBaur — APPROVED** [review]

**Review by chiragbajaj2010 — APPROVED** [review]

**Pull request merged**
